// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_lower_bound_index
int find_lower_bound_index(const Rcpp::NumericVector& L, const int start, const double tau);
RcppExport SEXP _nhppp_find_lower_bound_index(SEXP LSEXP, SEXP startSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type start(startSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(find_lower_bound_index(L, start, tau));
    return rcpp_result_gen;
END_RCPP
}
// find_upper_bound_index
int find_upper_bound_index(const Rcpp::NumericVector& L, const int start, const double tau);
RcppExport SEXP _nhppp_find_upper_bound_index(SEXP LSEXP, SEXP startSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type start(startSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(find_upper_bound_index(L, start, tau));
    return rcpp_result_gen;
END_RCPP
}
// matrix_cumsum_columns
Rcpp::NumericMatrix matrix_cumsum_columns(const Rcpp::NumericMatrix& X);
RcppExport SEXP _nhppp_matrix_cumsum_columns(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_cumsum_columns(X));
    return rcpp_result_gen;
END_RCPP
}
// matrix_cumsum_columns_inplace
void matrix_cumsum_columns_inplace(Rcpp::NumericMatrix& X);
RcppExport SEXP _nhppp_matrix_cumsum_columns_inplace(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type X(XSEXP);
    matrix_cumsum_columns_inplace(X);
    return R_NilValue;
END_RCPP
}
// matrix_diff_columns
Rcpp::NumericMatrix matrix_diff_columns(const Rcpp::NumericMatrix& X);
RcppExport SEXP _nhppp_matrix_diff_columns(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_diff_columns(X));
    return rcpp_result_gen;
END_RCPP
}
// matrix_diff_columns_inplace
void matrix_diff_columns_inplace(Rcpp::NumericMatrix& X);
RcppExport SEXP _nhppp_matrix_diff_columns_inplace(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type X(XSEXP);
    matrix_diff_columns_inplace(X);
    return R_NilValue;
END_RCPP
}
// rbtpois_vec
Rcpp::IntegerVector rbtpois_vec(const Rcpp::NumericVector& lambda, const int k_min, const int k_max);
RcppExport SEXP _nhppp_rbtpois_vec(SEXP lambdaSEXP, SEXP k_minSEXP, SEXP k_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type k_min(k_minSEXP);
    Rcpp::traits::input_parameter< const int >::type k_max(k_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(rbtpois_vec(lambda, k_min, k_max));
    return rcpp_result_gen;
END_RCPP
}
// rztpois
int rztpois(const double lambda);
RcppExport SEXP _nhppp_rztpois(SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(rztpois(lambda));
    return rcpp_result_gen;
END_RCPP
}
// rztpois_vec
Rcpp::IntegerVector rztpois_vec(const Rcpp::NumericVector& lambda);
RcppExport SEXP _nhppp_rztpois_vec(SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(rztpois_vec(lambda));
    return rcpp_result_gen;
END_RCPP
}
// vdraw_intensity_step_general
NumericMatrix vdraw_intensity_step_general(const Function& lambda, const NumericMatrix& rate_maj, const bool is_cumulative, const NumericMatrix& time_breaks, const NumericMatrix& subinterval, const bool use_subinterval, const double tol, const int report_first_K, const int report_last_K, const int gen_at_least_K, const int budget_cap);
RcppExport SEXP _nhppp_vdraw_intensity_step_general(SEXP lambdaSEXP, SEXP rate_majSEXP, SEXP is_cumulativeSEXP, SEXP time_breaksSEXP, SEXP subintervalSEXP, SEXP use_subintervalSEXP, SEXP tolSEXP, SEXP report_first_KSEXP, SEXP report_last_KSEXP, SEXP gen_at_least_KSEXP, SEXP budget_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Function& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type rate_maj(rate_majSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_cumulative(is_cumulativeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type time_breaks(time_breaksSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type subinterval(subintervalSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_subinterval(use_subintervalSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type report_first_K(report_first_KSEXP);
    Rcpp::traits::input_parameter< const int >::type report_last_K(report_last_KSEXP);
    Rcpp::traits::input_parameter< const int >::type gen_at_least_K(gen_at_least_KSEXP);
    Rcpp::traits::input_parameter< const int >::type budget_cap(budget_capSEXP);
    rcpp_result_gen = Rcpp::wrap(vdraw_intensity_step_general(lambda, rate_maj, is_cumulative, time_breaks, subinterval, use_subinterval, tol, report_first_K, report_last_K, gen_at_least_K, budget_cap));
    return rcpp_result_gen;
END_RCPP
}
// vdraw_intensity_step_regular
NumericMatrix vdraw_intensity_step_regular(const Function& lambda, const NumericMatrix& rate_maj, const bool is_cumulative, const NumericMatrix& range_t, const NumericMatrix& subinterval, const bool use_subinterval, const double tol, const int report_first_K, const int report_last_K, const int gen_at_least_K, const int budget_cap);
RcppExport SEXP _nhppp_vdraw_intensity_step_regular(SEXP lambdaSEXP, SEXP rate_majSEXP, SEXP is_cumulativeSEXP, SEXP range_tSEXP, SEXP subintervalSEXP, SEXP use_subintervalSEXP, SEXP tolSEXP, SEXP report_first_KSEXP, SEXP report_last_KSEXP, SEXP gen_at_least_KSEXP, SEXP budget_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Function& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type rate_maj(rate_majSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_cumulative(is_cumulativeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type range_t(range_tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type subinterval(subintervalSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_subinterval(use_subintervalSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type report_first_K(report_first_KSEXP);
    Rcpp::traits::input_parameter< const int >::type report_last_K(report_last_KSEXP);
    Rcpp::traits::input_parameter< const int >::type gen_at_least_K(gen_at_least_KSEXP);
    Rcpp::traits::input_parameter< const int >::type budget_cap(budget_capSEXP);
    rcpp_result_gen = Rcpp::wrap(vdraw_intensity_step_regular(lambda, rate_maj, is_cumulative, range_t, subinterval, use_subinterval, tol, report_first_K, report_last_K, gen_at_least_K, budget_cap));
    return rcpp_result_gen;
END_RCPP
}
// vdraw_sc_step_general2
NumericMatrix vdraw_sc_step_general2(const NumericMatrix& rate, const bool is_cumulative, const NumericMatrix& time_breaks, const NumericMatrix& subinterval, const double tol, const int report_first_K, const int report_last_K, const int budget_cap);
RcppExport SEXP _nhppp_vdraw_sc_step_general2(SEXP rateSEXP, SEXP is_cumulativeSEXP, SEXP time_breaksSEXP, SEXP subintervalSEXP, SEXP tolSEXP, SEXP report_first_KSEXP, SEXP report_last_KSEXP, SEXP budget_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_cumulative(is_cumulativeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type time_breaks(time_breaksSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type subinterval(subintervalSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type report_first_K(report_first_KSEXP);
    Rcpp::traits::input_parameter< const int >::type report_last_K(report_last_KSEXP);
    Rcpp::traits::input_parameter< const int >::type budget_cap(budget_capSEXP);
    rcpp_result_gen = Rcpp::wrap(vdraw_sc_step_general2(rate, is_cumulative, time_breaks, subinterval, tol, report_first_K, report_last_K, budget_cap));
    return rcpp_result_gen;
END_RCPP
}
// vdraw_sc_step_regular2
NumericMatrix vdraw_sc_step_regular2(const NumericMatrix& rate, const bool is_cumulative, const NumericMatrix& range_t, const NumericMatrix& subinterval, const double tol, const int report_first_K, const int report_last_K, const int budget_cap);
RcppExport SEXP _nhppp_vdraw_sc_step_regular2(SEXP rateSEXP, SEXP is_cumulativeSEXP, SEXP range_tSEXP, SEXP subintervalSEXP, SEXP tolSEXP, SEXP report_first_KSEXP, SEXP report_last_KSEXP, SEXP budget_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_cumulative(is_cumulativeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type range_t(range_tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type subinterval(subintervalSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type report_first_K(report_first_KSEXP);
    Rcpp::traits::input_parameter< const int >::type report_last_K(report_last_KSEXP);
    Rcpp::traits::input_parameter< const int >::type budget_cap(budget_capSEXP);
    rcpp_result_gen = Rcpp::wrap(vdraw_sc_step_regular2(rate, is_cumulative, range_t, subinterval, tol, report_first_K, report_last_K, budget_cap));
    return rcpp_result_gen;
END_RCPP
}
// vztdraw_sc_step_general2
NumericMatrix vztdraw_sc_step_general2(const NumericMatrix& rate, const bool is_cumulative, const NumericMatrix& time_breaks, const NumericMatrix& subinterval, const double tol, const int report_first_K, const int report_last_K, const int gen_at_least_K, const int gen_at_most_K, const int budget_cap);
RcppExport SEXP _nhppp_vztdraw_sc_step_general2(SEXP rateSEXP, SEXP is_cumulativeSEXP, SEXP time_breaksSEXP, SEXP subintervalSEXP, SEXP tolSEXP, SEXP report_first_KSEXP, SEXP report_last_KSEXP, SEXP gen_at_least_KSEXP, SEXP gen_at_most_KSEXP, SEXP budget_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_cumulative(is_cumulativeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type time_breaks(time_breaksSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type subinterval(subintervalSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type report_first_K(report_first_KSEXP);
    Rcpp::traits::input_parameter< const int >::type report_last_K(report_last_KSEXP);
    Rcpp::traits::input_parameter< const int >::type gen_at_least_K(gen_at_least_KSEXP);
    Rcpp::traits::input_parameter< const int >::type gen_at_most_K(gen_at_most_KSEXP);
    Rcpp::traits::input_parameter< const int >::type budget_cap(budget_capSEXP);
    rcpp_result_gen = Rcpp::wrap(vztdraw_sc_step_general2(rate, is_cumulative, time_breaks, subinterval, tol, report_first_K, report_last_K, gen_at_least_K, gen_at_most_K, budget_cap));
    return rcpp_result_gen;
END_RCPP
}
// vztdraw_sc_step_regular2
NumericMatrix vztdraw_sc_step_regular2(const NumericMatrix& rate, const bool is_cumulative, const NumericMatrix& range_t, const NumericMatrix& subinterval, const double tol, const int report_first_K, const int report_last_K, const int gen_at_least_K, const int gen_at_most_K, const int budget_cap);
RcppExport SEXP _nhppp_vztdraw_sc_step_regular2(SEXP rateSEXP, SEXP is_cumulativeSEXP, SEXP range_tSEXP, SEXP subintervalSEXP, SEXP tolSEXP, SEXP report_first_KSEXP, SEXP report_last_KSEXP, SEXP gen_at_least_KSEXP, SEXP gen_at_most_KSEXP, SEXP budget_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_cumulative(is_cumulativeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type range_t(range_tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type subinterval(subintervalSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type report_first_K(report_first_KSEXP);
    Rcpp::traits::input_parameter< const int >::type report_last_K(report_last_KSEXP);
    Rcpp::traits::input_parameter< const int >::type gen_at_least_K(gen_at_least_KSEXP);
    Rcpp::traits::input_parameter< const int >::type gen_at_most_K(gen_at_most_KSEXP);
    Rcpp::traits::input_parameter< const int >::type budget_cap(budget_capSEXP);
    rcpp_result_gen = Rcpp::wrap(vztdraw_sc_step_regular2(rate, is_cumulative, range_t, subinterval, tol, report_first_K, report_last_K, gen_at_least_K, gen_at_most_K, budget_cap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nhppp_find_lower_bound_index", (DL_FUNC) &_nhppp_find_lower_bound_index, 3},
    {"_nhppp_find_upper_bound_index", (DL_FUNC) &_nhppp_find_upper_bound_index, 3},
    {"_nhppp_matrix_cumsum_columns", (DL_FUNC) &_nhppp_matrix_cumsum_columns, 1},
    {"_nhppp_matrix_cumsum_columns_inplace", (DL_FUNC) &_nhppp_matrix_cumsum_columns_inplace, 1},
    {"_nhppp_matrix_diff_columns", (DL_FUNC) &_nhppp_matrix_diff_columns, 1},
    {"_nhppp_matrix_diff_columns_inplace", (DL_FUNC) &_nhppp_matrix_diff_columns_inplace, 1},
    {"_nhppp_rbtpois_vec", (DL_FUNC) &_nhppp_rbtpois_vec, 3},
    {"_nhppp_rztpois", (DL_FUNC) &_nhppp_rztpois, 1},
    {"_nhppp_rztpois_vec", (DL_FUNC) &_nhppp_rztpois_vec, 1},
    {"_nhppp_vdraw_intensity_step_general", (DL_FUNC) &_nhppp_vdraw_intensity_step_general, 11},
    {"_nhppp_vdraw_intensity_step_regular", (DL_FUNC) &_nhppp_vdraw_intensity_step_regular, 11},
    {"_nhppp_vdraw_sc_step_general2", (DL_FUNC) &_nhppp_vdraw_sc_step_general2, 8},
    {"_nhppp_vdraw_sc_step_regular2", (DL_FUNC) &_nhppp_vdraw_sc_step_regular2, 8},
    {"_nhppp_vztdraw_sc_step_general2", (DL_FUNC) &_nhppp_vztdraw_sc_step_general2, 10},
    {"_nhppp_vztdraw_sc_step_regular2", (DL_FUNC) &_nhppp_vztdraw_sc_step_regular2, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_nhppp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
