# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_ppp_cn <- function(rate, n, t_min) {
    .Call(`_nhppp_sim_ppp_cn`, rate, n, t_min)
}

sim_ppp_ct <- function(rate, t_min, t_max, tol = 10E-6) {
    .Call(`_nhppp_sim_ppp_ct`, rate, t_min, t_max, tol)
}

big_lambda <- function(t) {
    .Call(`_nhppp_big_lambda`, t)
}

big_lambda_inv <- function(z) {
    .Call(`_nhppp_big_lambda_inv`, z)
}

add <- function(x, y) {
    .Call(`_nhppp_add`, x, y)
}

multiply <- function(x, y) {
    .Call(`_nhppp_multiply`, x, y)
}

invoke <- function(x, y, int)) {
    .Call(`_nhppp_invoke`, x, y, int))
}

