# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_ppp_cn <- function(rate, n, t_min) {
    .Call(`_nhppp_sim_ppp_cn`, rate, n, t_min)
}

sim_ppp_ct <- function(rate, t_min, t_max, tol = 0.000001) {
    .Call(`_nhppp_sim_ppp_ct`, rate, t_min, t_max, tol)
}

